### ISSUE TITLE
Individual - Cloud Save/Restore - Trying to save cloud items produces error

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#56]
**Client Name:**  
Raynold

**Client ID:**  
21310

**Description:**  
Trying to cloud save data paths, billing, ero database, preparer etc. results in error.

**Reproduce:**  
Misc Features -> [30] Save cloud items
![image](https://user-images.githubusercontent.com/8196735/50566283-a31e5500-0cec-11e9-9db6-c48e2fb97aee.png)

```
Exception Found -
Type: System.Windows.Threading.DispatcherUnhandledExceptionEventArgs
Message: Object reference not set to an instance of an object.
Source: Wintax
Stacktrace:    at Wintax.FedPages.MiscFeatures.Scan_RunWorkerCompletedSave(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by MHGray** [comment]
Fixed in patch 1/3/18
